#!/usr/bin/perl -w

	use strict;
	use warnings;
	use Data::Dump qw(pp);
	use	SML::Document;
	
	print "START\n";
	
	my	$doc		= new SML::Document(); 
	my	$block1		= qx( cat block1.sml );
	my	$block2		= qx( cat block2.sml );
	my	$template1	= qx( cat template1.sml );
	

	print "PARSED\n";
	
	$doc->add_block( $block1 );
	$doc->add_block( $block2 );
	$doc->set_template( html => $template1 );
	
	print pp( $doc );
	